title: Jamie Pitts MBA
#logo: "/images/images.jpg?raw=true" # your photo (or logo) here
description: > 
  Credit Analyst with 7+ years of experience in consumer credit
  <br><br>
  4 years of credit analytics:
  Underwriting Methodology / Rules-based Prescreening / Delinquencies
  <br><br>
  2 years of corporate strategy:
  Product Mix, Operations Efficiency, Workflows, Collections Practices
  <br><br>
  4 years of risk analytics:
  Risk-based Pricing / Profitability / LTV
  <br><br>
  
  <a href="https://www.linkedin.com/in/J-Pitts/">View My LinkedIn Profile</a> 


theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
