title: Jamie Pitts # your name (or website title) here
logo: "/images/images.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Credit Analyst with 4+ years of experience in consumer credit analytics, strategy
  <br><br>
  Aspiring data scientist
  <br><br>
  <a href="https://www.linkedin.com/in/J-Pitts/">View My LinkedIn Profile</a> 


theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
