title: Jamie Pitts MBA# your name (or website title) here
logo: "/images/images.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Credit Analyst with 7+ years of experience in consumer credit
  <br><br>
  4 years of credit analytics -  Underwriting Methodology / Rules-based Prescreening / Delinquencies
  2 years of corporate strategy -  Product Mix, Operations Efficiency, Workflows, Collections Practices
  4 years of risk analytics - Risk-based Pricing / Profitability / LTV
  3 years of SQL, 2 years of Python
  <br><br>
  <a href="https://www.linkedin.com/in/J-Pitts/">View My LinkedIn Profile</a> 


theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
